### ISSUE TITLE
Consider adding a minimal Dockerfile extending rstudio/plumber

### ISSUE THREAD

**Issue by marioangst** [JosiahParry/valve#6]
One of the great things about plumber is how easy it is to get starting with testing to deploy it using the rstudio/plumber Docker image. 
For valve, it would make a lot of sense to give an example of a minimal dockerfile extending the rstudio/plumber image with valve.

**Comment by JosiahParry** [comment]
This is a great idea! I'll work on that. 

Would you expect a single vignette / article would suffice? Or would there need to be a template `Dockerfile` incuded with an R package for it?

**Comment by JosiahParry** [comment]
How is this article? 
https://valve.josiahparry.com/articles/using-valve-with-docker

**Comment by marioangst** [comment]
Amazing! I fixed some typos in a PR #7

**Comment by JosiahParry** [comment]
Thank you!
